navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: volantis-static/media/org.volantis/blog/Logo-NavBar@3x.png # https://gcore.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
    icon: https://mounui.com/wp-content/uploads/2017/09/favicon.png
    title:
  menu:
    - name: 博客
      icon: fa-solid fa-rss
      url: /